POST http://35.230.156.47/replay-detector
Content-Type: application/json
{
        "youtubeUrl": "https://www.youtube.com/watch?v=CWXhL_mMZ9A",
        "startFrame": 10000,
        "frameToAnalyse": 50000,
        "videoWidth": 150,
        "videoHeight": 150
}
