apiVersion: apps/v1
kind: Deployment
metadata:
  name: replaydetector-master
  labels:
    app: replaydetector
spec:
  selector:
    matchLabels:
      app: replaydetector
      role: master
      tier: backend
  replicas: 3
  template:
    metadata:
      labels:
        app: replaydetector
        role: master
        tier: backend
    spec:
      containers:
        - name: master
          image: replaydetector:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 8080
